### ISSUE TITLE
pip install lancet fails

### ISSUE THREAD

**Issue by Chive** [GaretJax/lancet#23]
Just so you don't forget :wink: 

```bash
❯ pipsi install lancet
New python executable in /Users/kim/.local/venvs/lancet/bin/python2.7
Also creating executable in /Users/kim/.local/venvs/lancet/bin/python
Installing setuptools, pip...done.
Collecting lancet
  Using cached lancet-0.7.1-py27-none-any.whl
Collecting gnureadline==6.3.3 (from lancet)
  Using cached gnureadline-6.3.3-cp27-none-macosx_10_5_x86_64.whl
Collecting six==1.9.0 (from lancet)
  Using cached six-1.9.0-py2.py3-none-any.whl
Collecting uritemplate.py==0.3.0 (from lancet)
  Using cached uritemplate.py-0.3.0.tar.gz
Collecting tlslite==0.4.8 (from lancet)
  Using cached tlslite-0.4.8.tar.gz
Collecting keyring==5.3 (from lancet)
  Using cached keyring-5.3.zip
Collecting Unidecode==0.04.17 (from lancet)
  Using cached Unidecode-0.04.17.tar.gz
Collecting MarkupSafe==0.23 (from lancet)
  Using cached MarkupSafe-0.23.tar.gz
Collecting click==3.3 (from lancet)
  Using cached click-3.3-py2.py3-none-any.whl
Collecting requests==2.5.3 (from lancet)
  Using cached requests-2.5.3-py2.py3-none-any.whl
Collecting oauthlib==0.7.2 (from lancet)
  Using cached oauthlib-0.7.2.tar.gz
Collecting giturlparse.py==0.0.5 (from lancet)
  Using cached giturlparse.py-0.0.5.tar.gz
Collecting pygit2==0.21.4 (from lancet)
  Using cached pygit2-0.21.4.tar.gz
    Complete output from command python setup.py egg_info:
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    In file included from c/_cffi_backend.c:5902:
    c/../_cffi1/cffi1_module.c:21:34: warning: comparison of constant 0 with boolean expression is always false [-Wtautological-constant-out-of-range-compare]
        if (!PyType_Ready(&FFI_Type) < 0)
            ~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
    c/../_cffi1/cffi1_module.c:23:34: warning: comparison of constant 0 with boolean expression is always false [-Wtautological-constant-out-of-range-compare]
        if (!PyType_Ready(&Lib_Type) < 0)
            ~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
    2 warnings generated.

    Installed /private/var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/pip-build-FjbOIy/pygit2/.eggs/cffi-1.0.0b2-py2.7-macosx-10.10-x86_64.egg
    Searching for pycparser
    Reading https://pypi.python.org/simple/pycparser/
    Best match: pycparser 2.12
    Downloading https://pypi.python.org/packages/source/p/pycparser/pycparser-2.12.tar.gz#md5=debde3e37af8566c95d2c0a0504397e7
    Processing pycparser-2.12.tar.gz
    Writing /var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/easy_install-iQfqta/pycparser-2.12/setup.cfg
    Running pycparser-2.12/setup.py -q bdist_egg --dist-dir /var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/easy_install-iQfqta/pycparser-2.12/egg-dist-tmp-PROghF
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
    zip_safe flag not set; analyzing archive contents...
    Copying pycparser-2.12-py2.7.egg to /private/var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/pip-build-FjbOIy/pygit2/.eggs

    Installed /private/var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/pip-build-FjbOIy/pygit2/.eggs/pycparser-2.12-py2.7.egg
    running egg_info
    creating pip-egg-info/pygit2.egg-info
    writing requirements to pip-egg-info/pygit2.egg-info/requires.txt
    writing pip-egg-info/pygit2.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/pygit2.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/pygit2.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/pygit2.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    running build_ext
    building 'pygit2_cffi_bd4f3739x292444b7' extension
    creating /private/var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/pip-build-FjbOIy/pygit2/pygit2/__pycache__/pygit2
    creating /private/var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/pip-build-FjbOIy/pygit2/pygit2/__pycache__/pygit2/__pycache__
    clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -I/usr/local/include -I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pygit2/__pycache__/pygit2_cffi_bd4f3739x292444b7.c -o /private/var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/pip-build-FjbOIy/pygit2/pygit2/__pycache__/pygit2/__pycache__/pygit2_cffi_bd4f3739x292444b7.o
    pygit2/__pycache__/pygit2_cffi_bd4f3739x292444b7.c:207:10: fatal error: 'git2.h' file not found
    #include <git2.h>
             ^
    1 error generated.
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/pip-build-FjbOIy/pygit2/setup.py", line 202, in <module>
        cmdclass=cmdclass)
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "<string>", line 15, in replacement_run
      File "/Users/kim/.local/venvs/lancet/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 207, in find_sources
        mm.run()
      File "/Users/kim/.local/venvs/lancet/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 291, in run
        self.add_defaults()
      File "/Users/kim/.local/venvs/lancet/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 320, in add_defaults
        sdist.add_defaults(self)
      File "/Users/kim/.local/venvs/lancet/lib/python2.7/site-packages/setuptools/command/sdist.py", line 118, in add_defaults
        build_py = self.get_finalized_command('build_py')
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "/Users/kim/.local/venvs/lancet/lib/python2.7/site-packages/setuptools/command/build_py.py", line 28, in finalize_options
        orig.build_py.finalize_options(self)
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_py.py", line 46, in finalize_options
        ('force', 'force'))
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 298, in set_undefined_options
        src_cmd_obj.ensure_finalized()
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "/private/var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/pip-build-FjbOIy/pygit2/setup.py", line 101, in finalize_options
        ffi, C = get_ffi()
      File "pygit2/_utils.py", line 101, in get_ffi
        include_dirs=[libgit2_include], library_dirs=[libgit2_lib])
      File "/private/var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/pip-build-FjbOIy/pygit2/.eggs/cffi-1.0.0b2-py2.7-macosx-10.10-x86_64.egg/cffi/api.py", line 368, in verify
        lib = self.verifier.load_library()
      File "/private/var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/pip-build-FjbOIy/pygit2/.eggs/cffi-1.0.0b2-py2.7-macosx-10.10-x86_64.egg/cffi/verifier.py", line 96, in load_library
        self._compile_module()
      File "/private/var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/pip-build-FjbOIy/pygit2/.eggs/cffi-1.0.0b2-py2.7-macosx-10.10-x86_64.egg/cffi/verifier.py", line 192, in _compile_module
        outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
      File "/private/var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/pip-build-FjbOIy/pygit2/.eggs/cffi-1.0.0b2-py2.7-macosx-10.10-x86_64.egg/cffi/ffiplatform.py", line 38, in compile
        outputfilename = _build(tmpdir, ext)
      File "/private/var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/pip-build-FjbOIy/pygit2/.eggs/cffi-1.0.0b2-py2.7-macosx-10.10-x86_64.egg/cffi/ffiplatform.py", line 65, in _build
        raise VerificationError('%s: %s' % (e.__class__.__name__, e))
    cffi.ffiplatform.VerificationError: CompileError: command 'clang' failed with exit status 1

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/pip-build-FjbOIy/pygit2
Failed to pip install.  Aborting.
```

**Comment by GaretJax** [comment]
Fixed with the latest release.

**Comment by Chive** [comment]
Same issue again @GaretJax  :( 

```bash
(env)❯ pip install lancet
Collecting lancet
  Using cached lancet-0.7.6.tar.gz
Collecting cffi==1.1.2 (from lancet)
Collecting click==4.0 (from lancet)
  Using cached click-4.0-py2.py3-none-any.whl
Collecting gnureadline==6.3.3 (from lancet)
  Using cached gnureadline-6.3.3-cp27-none-macosx_10_5_x86_64.whl
Collecting jira==0.47 (from lancet)
  Using cached jira-0.47-py2.py3-none-any.whl
Collecting keyring==5.3 (from lancet)
Collecting oauthlib==0.7.2 (from lancet)
Collecting pycparser==2.14 (from lancet)
Collecting pygit2==0.22.0 (from lancet)
  Using cached pygit2-0.22.0.tar.gz
    Complete output from command python setup.py egg_info:
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found

    Installed /private/var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/pip-build-qx7ZC8/pygit2/.eggs/cffi-1.2.1-py2.7-macosx-10.10-x86_64.egg
    Searching for pycparser
    Reading https://pypi.python.org/simple/pycparser/
    Best match: pycparser 2.14
    Downloading https://pypi.python.org/packages/source/p/pycparser/pycparser-2.14.tar.gz#md5=a2bc8d28c923b4fe2b2c3b4b51a4f935
    Processing pycparser-2.14.tar.gz
    Writing /var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/easy_install-8EVetg/pycparser-2.14/setup.cfg
    Running pycparser-2.14/setup.py -q bdist_egg --dist-dir /var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/easy_install-8EVetg/pycparser-2.14/egg-dist-tmp-sjjcY6
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
    zip_safe flag not set; analyzing archive contents...
    Copying pycparser-2.14-py2.7.egg to /private/var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/pip-build-qx7ZC8/pygit2/.eggs

    Installed /private/var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/pip-build-qx7ZC8/pygit2/.eggs/pycparser-2.14-py2.7.egg
    running egg_info
    creating pip-egg-info/pygit2.egg-info
    writing requirements to pip-egg-info/pygit2.egg-info/requires.txt
    writing pip-egg-info/pygit2.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/pygit2.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/pygit2.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/pygit2.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    running build_ext
    building 'pygit2_cffi_2c88a0e0x5470904' extension
    creating /private/var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/pip-build-qx7ZC8/pygit2/pygit2/__pycache__/pygit2
    creating /private/var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/pip-build-qx7ZC8/pygit2/pygit2/__pycache__/pygit2/__pycache__
    clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -I/usr/local/include -I/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pygit2/__pycache__/pygit2_cffi_2c88a0e0x5470904.c -o /private/var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/pip-build-qx7ZC8/pygit2/pygit2/__pycache__/pygit2/__pycache__/pygit2_cffi_2c88a0e0x5470904.o
    pygit2/__pycache__/pygit2_cffi_2c88a0e0x5470904.c:1048:8: error: use of undeclared identifier 'GIT_EMERGECONFLICT'; did you mean 'GIT_ECONFLICT'?
      if ((GIT_EMERGECONFLICT) > 0 || (long)(GIT_EMERGECONFLICT) != -13L) {
           ^~~~~~~~~~~~~~~~~~
           GIT_ECONFLICT
    /usr/local/include/git2/errors.h:41:2: note: 'GIT_ECONFLICT' declared here
            GIT_ECONFLICT       = -13,      /**< Checkout conflicts prevented operation */
            ^
    pygit2/__pycache__/pygit2_cffi_2c88a0e0x5470904.c:1048:42: error: use of undeclared identifier 'GIT_EMERGECONFLICT'; did you mean 'GIT_ECONFLICT'?
      if ((GIT_EMERGECONFLICT) > 0 || (long)(GIT_EMERGECONFLICT) != -13L) {
                                             ^~~~~~~~~~~~~~~~~~
                                             GIT_ECONFLICT
    /usr/local/include/git2/errors.h:41:2: note: 'GIT_ECONFLICT' declared here
            GIT_ECONFLICT       = -13,      /**< Checkout conflicts prevented operation */
            ^
    pygit2/__pycache__/pygit2_cffi_2c88a0e0x5470904.c:1050:10: error: use of undeclared identifier 'GIT_EMERGECONFLICT'; did you mean 'GIT_ECONFLICT'?
        if ((GIT_EMERGECONFLICT) <= 0)
             ^~~~~~~~~~~~~~~~~~
             GIT_ECONFLICT
    /usr/local/include/git2/errors.h:41:2: note: 'GIT_ECONFLICT' declared here
            GIT_ECONFLICT       = -13,      /**< Checkout conflicts prevented operation */
            ^
    pygit2/__pycache__/pygit2_cffi_2c88a0e0x5470904.c:1051:41: error: use of undeclared identifier 'GIT_EMERGECONFLICT'; did you mean 'GIT_ECONFLICT'?
            snprintf(buf, 63, "%ld", (long)(GIT_EMERGECONFLICT));
                                            ^~~~~~~~~~~~~~~~~~
                                            GIT_ECONFLICT
    /usr/include/secure/_stdio.h:57:62: note: expanded from macro 'snprintf'
      __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                                                                 ^
    /usr/local/include/git2/errors.h:41:2: note: 'GIT_ECONFLICT' declared here
            GIT_ECONFLICT       = -13,      /**< Checkout conflicts prevented operation */
            ^
    pygit2/__pycache__/pygit2_cffi_2c88a0e0x5470904.c:1053:50: error: use of undeclared identifier 'GIT_EMERGECONFLICT'; did you mean 'GIT_ECONFLICT'?
            snprintf(buf, 63, "%lu", (unsigned long)(GIT_EMERGECONFLICT));
                                                     ^~~~~~~~~~~~~~~~~~
                                                     GIT_ECONFLICT
    /usr/include/secure/_stdio.h:57:62: note: expanded from macro 'snprintf'
      __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                                                                 ^
    /usr/local/include/git2/errors.h:41:2: note: 'GIT_ECONFLICT' declared here
            GIT_ECONFLICT       = -13,      /**< Checkout conflicts prevented operation */
            ^
    pygit2/__pycache__/pygit2_cffi_2c88a0e0x5470904.c:1176:38: error: no member named 'flags' in 'git_merge_options'
      { git_merge_tree_flag_t *tmp = &p->flags; (void)tmp; }
                                      ~  ^
    pygit2/__pycache__/pygit2_cffi_2c88a0e0x5470904.c:1191:5: error: no member named 'flags' in ''
        offsetof(git_merge_options, flags),
        ^                           ~~~~~
    /Library/Developer/CommandLineTools/usr/bin/../lib/clang/6.1.0/include/stddef.h:133:24: note: expanded from macro 'offsetof'
    #define offsetof(t, d) __builtin_offsetof(t, d)
                           ^
    pygit2/__pycache__/pygit2_cffi_2c88a0e0x5470904.c:1192:38: error: no member named 'flags' in 'git_merge_options'
        sizeof(((git_merge_options *)0)->flags),
               ~~~~~~~~~~~~~~~~~~~~~~~~  ^
    pygit2/__pycache__/pygit2_cffi_2c88a0e0x5470904.c:1459:8: error: use of undeclared identifier 'GIT_SUBMODULE_IGNORE_RESET'; did you mean 'GIT_SUBMODULE_IGNORE_NONE'?
      if ((GIT_SUBMODULE_IGNORE_RESET) > 0 || (long)(GIT_SUBMODULE_IGNORE_RESET) != -1L) {
           ^~~~~~~~~~~~~~~~~~~~~~~~~~
           GIT_SUBMODULE_IGNORE_NONE
    /usr/local/include/git2/types.h:402:2: note: 'GIT_SUBMODULE_IGNORE_NONE' declared here
            GIT_SUBMODULE_IGNORE_NONE      = 1,  /**< any change or untracked == dirty */
            ^
    pygit2/__pycache__/pygit2_cffi_2c88a0e0x5470904.c:1459:50: error: use of undeclared identifier 'GIT_SUBMODULE_IGNORE_RESET'; did you mean 'GIT_SUBMODULE_IGNORE_NONE'?
      if ((GIT_SUBMODULE_IGNORE_RESET) > 0 || (long)(GIT_SUBMODULE_IGNORE_RESET) != -1L) {
                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                                     GIT_SUBMODULE_IGNORE_NONE
    /usr/local/include/git2/types.h:402:2: note: 'GIT_SUBMODULE_IGNORE_NONE' declared here
            GIT_SUBMODULE_IGNORE_NONE      = 1,  /**< any change or untracked == dirty */
            ^
    pygit2/__pycache__/pygit2_cffi_2c88a0e0x5470904.c:1461:10: error: use of undeclared identifier 'GIT_SUBMODULE_IGNORE_RESET'; did you mean 'GIT_SUBMODULE_IGNORE_NONE'?
        if ((GIT_SUBMODULE_IGNORE_RESET) <= 0)
             ^~~~~~~~~~~~~~~~~~~~~~~~~~
             GIT_SUBMODULE_IGNORE_NONE
    /usr/local/include/git2/types.h:402:2: note: 'GIT_SUBMODULE_IGNORE_NONE' declared here
            GIT_SUBMODULE_IGNORE_NONE      = 1,  /**< any change or untracked == dirty */
            ^
    pygit2/__pycache__/pygit2_cffi_2c88a0e0x5470904.c:1462:41: error: use of undeclared identifier 'GIT_SUBMODULE_IGNORE_RESET'; did you mean 'GIT_SUBMODULE_IGNORE_NONE'?
            snprintf(buf, 63, "%ld", (long)(GIT_SUBMODULE_IGNORE_RESET));
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                            GIT_SUBMODULE_IGNORE_NONE
    /usr/include/secure/_stdio.h:57:62: note: expanded from macro 'snprintf'
      __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                                                                 ^
    /usr/local/include/git2/types.h:402:2: note: 'GIT_SUBMODULE_IGNORE_NONE' declared here
            GIT_SUBMODULE_IGNORE_NONE      = 1,  /**< any change or untracked == dirty */
            ^
    pygit2/__pycache__/pygit2_cffi_2c88a0e0x5470904.c:1464:50: error: use of undeclared identifier 'GIT_SUBMODULE_IGNORE_RESET'; did you mean 'GIT_SUBMODULE_IGNORE_NONE'?
            snprintf(buf, 63, "%lu", (unsigned long)(GIT_SUBMODULE_IGNORE_RESET));
                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                                     GIT_SUBMODULE_IGNORE_NONE
    /usr/include/secure/_stdio.h:57:62: note: expanded from macro 'snprintf'
      __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                                                                 ^
    /usr/local/include/git2/types.h:402:2: note: 'GIT_SUBMODULE_IGNORE_NONE' declared here
            GIT_SUBMODULE_IGNORE_NONE      = 1,  /**< any change or untracked == dirty */
            ^
    pygit2/__pycache__/pygit2_cffi_2c88a0e0x5470904.c:1514:8: error: use of undeclared identifier 'GIT_SUBMODULE_IGNORE_DEFAULT'
      if ((GIT_SUBMODULE_IGNORE_DEFAULT) > 0 || (long)(GIT_SUBMODULE_IGNORE_DEFAULT) != 0L) {
           ^
    pygit2/__pycache__/pygit2_cffi_2c88a0e0x5470904.c:1514:52: error: use of undeclared identifier 'GIT_SUBMODULE_IGNORE_DEFAULT'
      if ((GIT_SUBMODULE_IGNORE_DEFAULT) > 0 || (long)(GIT_SUBMODULE_IGNORE_DEFAULT) != 0L) {
                                                       ^
    pygit2/__pycache__/pygit2_cffi_2c88a0e0x5470904.c:1516:10: error: use of undeclared identifier 'GIT_SUBMODULE_IGNORE_DEFAULT'
        if ((GIT_SUBMODULE_IGNORE_DEFAULT) <= 0)
             ^
    pygit2/__pycache__/pygit2_cffi_2c88a0e0x5470904.c:1517:41: error: use of undeclared identifier 'GIT_SUBMODULE_IGNORE_DEFAULT'
            snprintf(buf, 63, "%ld", (long)(GIT_SUBMODULE_IGNORE_DEFAULT));
                                            ^
    /usr/include/secure/_stdio.h:57:62: note: expanded from macro 'snprintf'
      __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                                                                 ^
    pygit2/__pycache__/pygit2_cffi_2c88a0e0x5470904.c:1519:50: error: use of undeclared identifier 'GIT_SUBMODULE_IGNORE_DEFAULT'
            snprintf(buf, 63, "%lu", (unsigned long)(GIT_SUBMODULE_IGNORE_DEFAULT));
                                                     ^
    /usr/include/secure/_stdio.h:57:62: note: expanded from macro 'snprintf'
      __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                                                                 ^
    pygit2/__pycache__/pygit2_cffi_2c88a0e0x5470904.c:4972:41: error: too few arguments to function call, expected 3, have 2
      { result = git_remote_add_fetch(x0, x1); }
                 ~~~~~~~~~~~~~~~~~~~~       ^
    /usr/local/include/git2/remote.h:179:1: note: 'git_remote_add_fetch' declared here
    GIT_EXTERN(int) git_remote_add_fetch(git_repository *repo, const char *remote, const char *refspec);
    ^
    /usr/local/include/git2/common.h:31:27: note: expanded from macro 'GIT_EXTERN'
    # define GIT_EXTERN(type) extern \
                              ^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/pip-build-qx7ZC8/pygit2/setup.py", line 197, in <module>
        cmdclass=cmdclass)
      File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "<string>", line 15, in replacement_run
      File "/private/tmp/env/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 207, in find_sources
        mm.run()
      File "/private/tmp/env/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 291, in run
        self.add_defaults()
      File "/private/tmp/env/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 320, in add_defaults
        sdist.add_defaults(self)
      File "/private/tmp/env/lib/python2.7/site-packages/setuptools/command/sdist.py", line 118, in add_defaults
        build_py = self.get_finalized_command('build_py')
      File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "/private/tmp/env/lib/python2.7/site-packages/setuptools/command/build_py.py", line 28, in finalize_options
        orig.build_py.finalize_options(self)
      File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_py.py", line 46, in finalize_options
        ('force', 'force'))
      File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 298, in set_undefined_options
        src_cmd_obj.ensure_finalized()
      File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "/private/var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/pip-build-qx7ZC8/pygit2/setup.py", line 103, in finalize_options
        ffi, C = get_ffi()
      File "pygit2/_utils.py", line 101, in get_ffi
        include_dirs=[libgit2_include], library_dirs=[libgit2_lib])
      File "/private/var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/pip-build-qx7ZC8/pygit2/.eggs/cffi-1.2.1-py2.7-macosx-10.10-x86_64.egg/cffi/api.py", line 405, in verify
        lib = self.verifier.load_library()
      File "/private/var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/pip-build-qx7ZC8/pygit2/.eggs/cffi-1.2.1-py2.7-macosx-10.10-x86_64.egg/cffi/verifier.py", line 100, in load_library
        self._compile_module()
      File "/private/var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/pip-build-qx7ZC8/pygit2/.eggs/cffi-1.2.1-py2.7-macosx-10.10-x86_64.egg/cffi/verifier.py", line 196, in _compile_module
        outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
      File "/private/var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/pip-build-qx7ZC8/pygit2/.eggs/cffi-1.2.1-py2.7-macosx-10.10-x86_64.egg/cffi/ffiplatform.py", line 38, in compile
        outputfilename = _build(tmpdir, ext)
      File "/private/var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/pip-build-qx7ZC8/pygit2/.eggs/cffi-1.2.1-py2.7-macosx-10.10-x86_64.egg/cffi/ffiplatform.py", line 65, in _build
        raise VerificationError('%s: %s' % (e.__class__.__name__, e))
    cffi.ffiplatform.VerificationError: CompileError: command 'clang' failed with exit status 1

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/90/c8vt49x94657zkzbgqc8t3yh0000gn/T/pip-build-qx7ZC8/pygit2
```
